spring.application.name=TP_prg3
# Configuraci�n de la base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/proyecto_comercio
spring.datasource.username=root
spring.datasource.password=4861944
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuraci�n de JPA (Hibernate)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.address=0.0.0.0
server.port=8080